-- Approval queue: drafts generated by triggers when the effective review policy
-- is 'review'. Per spec §2.4: "every trigger produces a draft; nothing ever sends
-- without agent approval in the first 30 days."
--
-- Real send (status='sent') requires a Twilio/SendGrid integration — not in this
-- PR. `approve` moves the status to 'approved' and stamps approved_at; a future
-- sender worker reads `status='approved'` rows and dispatches.

create table if not exists public.message_drafts (
  id uuid primary key default gen_random_uuid(),
  agent_id uuid null,     -- populated via trigger below from contact.agent_id
  contact_id uuid not null references public.sphere_contacts(id) on delete cascade,
  template_id text null references public.templates(id) on delete set null,
  -- Free-form for drafts that aren't tied to a template (manual compose).
  channel text not null check (channel in ('sms', 'email')),
  subject text null,
  body text not null,
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected', 'sent', 'failed')),
  -- Why the trigger fired (signal id, threshold crossed, etc.). Optional.
  trigger_context jsonb not null default '{}'::jsonb,
  -- Who edited the draft before approving (nullable; null = sent as-rendered).
  edited boolean not null default false,
  created_at timestamptz not null default now(),
  approved_at timestamptz null,
  rejected_at timestamptz null,
  rejected_reason text null,
  sent_at timestamptz null,
  failed_at timestamptz null,
  failure_reason text null,
  -- Soft target send time (so quiet-hours respect can delay an approved draft).
  scheduled_for timestamptz null
);

create index if not exists idx_message_drafts_agent_status
  on public.message_drafts(agent_id, status);
create index if not exists idx_message_drafts_contact
  on public.message_drafts(contact_id);
create index if not exists idx_message_drafts_pending
  on public.message_drafts(agent_id, created_at desc)
  where status = 'pending';

-- Populate agent_id automatically from the contact so the caller doesn't have
-- to pass it + the agent check can stay on the single indexed column.
create or replace function public.message_drafts_set_agent_id()
returns trigger
language plpgsql
as $$
begin
  if new.agent_id is null then
    select c.agent_id into new.agent_id
    from public.sphere_contacts c
    where c.id = new.contact_id;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_message_drafts_set_agent_id on public.message_drafts;
create trigger trg_message_drafts_set_agent_id
  before insert on public.message_drafts
  for each row
  execute function public.message_drafts_set_agent_id();

comment on table public.message_drafts is
  'Approval queue for Review-mode messages. Populated by triggers; cleared by agent approve/reject. Spec §2.4.';
comment on column public.message_drafts.status is
  'Lifecycle: pending → approved → sent (worker), or pending → rejected, or sent → failed.';
