-- Per-agent media library for the Generate Leads feature.
--
-- Two pieces:
--   1. `media_library` table — metadata for each uploaded media item
--      (storage path, original filename, kind, optional listing
--      back-reference, etc).
--   2. `lead-media` storage bucket — private, served via signed URLs
--      from the API. Per-agent isolation enforced at the API layer
--      (service-role admin client + explicit agent_id check), not via
--      storage RLS policies — keeps the policy surface small and
--      mirrors how the contact_import_jobs intake works.
--
-- agents.id is bigint (confirmed via pg_attribute on prod 2026-05-12).
-- If a future dev env uses uuid, the bigint reference would fail
-- loudly at apply-time — we'd add the dual-type guard from the
-- legacy contact_import_jobs migration at that point.

create table if not exists public.media_library (
  id uuid primary key default gen_random_uuid(),
  agent_id bigint not null references public.agents (id) on delete cascade,
  -- Path inside the lead-media bucket. We always namespace by
  -- agent_id (e.g. "<agent_id>/<uuid>.<ext>") so a bucket-wide
  -- listing groups cleanly per agent, and a future per-agent
  -- delete is a single prefix-scoped delete on the bucket.
  storage_path text not null,
  -- Optional public-ish URL — set when the upload uses a public
  -- bucket or after a long-lived signed URL is materialized. The
  -- API layer always re-signs at read-time, so this is mostly an
  -- audit/debug field. Nullable.
  public_url text,
  kind text not null default 'general'
    check (kind in ('general', 'listing_photo', 'agent_headshot', 'agent_logo', 'market_chart', 'testimonial_quote')),
  -- How the item got into the library:
  --   'upload'        — agent uploaded a file via the wizard
  --   'listing_photo' — auto-imported from a listing's photo set
  --   'derived'       — generated by an AI tool (future)
  source text not null default 'upload'
    check (source in ('upload', 'listing_photo', 'derived')),
  related_listing_id uuid null references public.listings (id) on delete set null,
  -- Original filename + content-type for display + Meta-API attachment
  -- in Phase 2 (Meta wants the MIME and a sensible filename for
  -- Lead-Ad creative).
  file_name text,
  content_type text,
  size_bytes bigint,
  -- Optional agent-supplied label / alt text.
  label text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists media_library_agent_id_idx
  on public.media_library (agent_id, created_at desc);

create index if not exists media_library_listing_idx
  on public.media_library (related_listing_id)
  where related_listing_id is not null;

comment on table public.media_library is
  'Per-agent media library for the Generate Leads feature. Storage lives in the `lead-media` bucket; this table is metadata only.';

-- Private bucket. Service-role uploads + signed-URL reads from API.
-- Public=false so a leaked storage_path can''t be fetched without a
-- signed URL.
--
-- 20 MB file cap matches the AI-extract-from-file path (PR #387);
-- agents uploading larger assets (4K listing photos) can hit
-- AGENT_MEDIA_MAX_BYTES if we ever need to raise it.
--
-- MIME list intentionally narrow — only image formats the Quick
-- Post + Meta Lead Ad surfaces will actually use. PDF / video
-- can be added later when those surfaces ship.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'lead-media',
  'lead-media',
  false,
  20971520,
  array[
    'image/jpeg',
    'image/jpg',
    'image/png',
    'image/webp',
    'image/gif',
    'image/heic',
    'image/heif'
  ]::text[]
)
on conflict (id) do update set
  name = excluded.name,
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
