import { StyleSheet } from "react-native";
import { theme } from "../theme";

export const onboardingStyles = StyleSheet.create({
  flex: { flex: 1, backgroundColor: theme.bg },
  safePad: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 56,
    paddingBottom: 32,
    justifyContent: "space-between",
  },
  centerBlock: { flex: 1, justifyContent: "center" },
  kicker: {
    fontSize: 13,
    fontWeight: "700",
    color: theme.accent,
    letterSpacing: 1.2,
    marginBottom: 12,
    textTransform: "uppercase",
  },
  title: {
    fontSize: 28,
    fontWeight: "800",
    color: theme.text,
    lineHeight: 34,
    marginBottom: 12,
  },
  body: {
    fontSize: 16,
    color: theme.textMuted,
    lineHeight: 24,
  },
  primaryBtn: {
    backgroundColor: theme.accent,
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: "center",
  },
  primaryBtnText: { color: "#fff", fontSize: 16, fontWeight: "700" },
  secondaryBtn: {
    marginTop: 12,
    paddingVertical: 14,
    alignItems: "center",
  },
  secondaryBtnText: { color: theme.accent, fontSize: 15, fontWeight: "600" },
  muted: { fontSize: 13, color: theme.textSubtle, marginTop: 16, lineHeight: 20 },
  pagerDotRow: { flexDirection: "row", justifyContent: "center", gap: 8, marginTop: 24 },
  dot: { width: 8, height: 8, borderRadius: 4, backgroundColor: theme.border },
  dotActive: { backgroundColor: theme.accent, width: 22 },
  input: {
    marginTop: 20,
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 14,
    fontSize: 15,
    color: theme.text,
    backgroundColor: theme.surface,
    minHeight: 120,
    textAlignVertical: "top",
  },
  error: { marginTop: 12, fontSize: 14, color: theme.errorTitle },
});
