import { jsPDF } from "jspdf";
import type {
  DealAnalyzerInputs,
  DealAnalyzerMetrics,
  DealCommentary,
} from "./types";
import type { SensitivityTable } from "./sensitivity";

/**
 * Client-side PDF builder for the AI deal analyzer. Two pages:
 *   1. Headline score, key metrics, AI strengths / risks / next moves
 *   2. Full input recap + sensitivity tables
 *
 * Pure function — returns the jsPDF instance. Caller calls `.save()`
 * or pipes the blob however they like.
 */

const MARGIN = 15; // mm — usable page area starts here
const PAGE_WIDTH = 210;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

export function buildDealAnalyzerPdf(opts: {
  inputs: DealAnalyzerInputs;
  metrics: DealAnalyzerMetrics;
  commentary: DealCommentary;
  sensitivity: SensitivityTable[];
  generatedAtIso?: string;
}): jsPDF {
  const { inputs, metrics, commentary, sensitivity } = opts;
  const generatedAt = opts.generatedAtIso
    ? new Date(opts.generatedAtIso)
    : new Date();
  const doc = new jsPDF({ unit: "mm", format: "a4" });

  // ── Page 1 ─────────────────────────────────────────────────────
  let y = MARGIN;

  // Header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(30, 41, 59);
  doc.text("AI Deal Analyzer Report", MARGIN, y);
  y += 7;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text(
    inputs.propertyAddress || "(property address not provided)",
    MARGIN,
    y,
  );
  y += 5;
  doc.setFontSize(8);
  doc.text(
    `Generated ${generatedAt.toLocaleString(undefined, { dateStyle: "medium", timeStyle: "short" })}`,
    MARGIN,
    y,
  );
  y += 8;

  // Deal score banner
  doc.setFillColor(
    commentary.dealScore >= 70 ? 34 : commentary.dealScore >= 50 ? 234 : 220,
    commentary.dealScore >= 70 ? 197 : commentary.dealScore >= 50 ? 179 : 38,
    commentary.dealScore >= 70 ? 94 : commentary.dealScore >= 50 ? 8 : 38,
  );
  doc.rect(MARGIN, y, CONTENT_WIDTH, 18, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(28);
  doc.text(`${commentary.dealScore}/100`, MARGIN + 4, y + 13);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text(commentary.headline, MARGIN + 40, y + 11);
  y += 24;

  // Key metrics row
  doc.setTextColor(30, 41, 59);
  const metricRow: Array<[string, string]> = [
    ["Monthly cash flow", fmtUSD(metrics.monthlyCashFlow)],
    ["Cap rate", `${metrics.capRate.toFixed(2)}%`],
    ["CoC return", `${metrics.cashOnCashReturn.toFixed(2)}%`],
    ["Price/rent", metrics.priceToRentRatio.toFixed(1)],
  ];
  const colWidth = CONTENT_WIDTH / metricRow.length;
  metricRow.forEach(([label, val], i) => {
    const x = MARGIN + i * colWidth;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.text(label.toUpperCase(), x, y);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(15, 23, 42);
    doc.text(val, x, y + 6);
  });
  y += 14;

  // Summary
  y = drawSection(doc, "Summary", y);
  y = drawParagraph(doc, commentary.summary, y);
  y += 3;

  // Strengths
  y = drawSection(doc, "Strengths", y);
  y = drawBullets(doc, commentary.strengths, y);
  y += 3;

  // Risks
  y = drawSection(doc, "Risks", y);
  y = drawBullets(doc, commentary.risks, y);
  y += 3;

  // Next moves
  y = drawSection(doc, "Next moves", y);
  y = drawBullets(doc, commentary.nextMoves, y);

  // Footer disclaimer
  doc.setFont("helvetica", "italic");
  doc.setFontSize(7);
  doc.setTextColor(148, 163, 184);
  doc.text(
    commentary.aiGenerated
      ? "Commentary generated by Claude based on your inputs. Not financial advice — verify with a local expert."
      : "Commentary generated from deterministic rules (AI unavailable). Not financial advice.",
    MARGIN,
    285,
    { maxWidth: CONTENT_WIDTH },
  );

  // ── Page 2 ─────────────────────────────────────────────────────
  doc.addPage();
  y = MARGIN;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(30, 41, 59);
  doc.text("Inputs & sensitivity", MARGIN, y);
  y += 8;

  // Inputs recap
  y = drawSection(doc, "Your assumptions", y);
  const inputPairs: Array<[string, string]> = [
    ["Purchase price", fmtUSD(inputs.purchasePrice)],
    ["Down payment", `${inputs.downPaymentPercent}% (${fmtUSD((inputs.purchasePrice * inputs.downPaymentPercent) / 100)})`],
    ["Loan", `${fmtUSD(metrics.loanAmount)} @ ${inputs.interestRate}% / ${inputs.loanTermYears} yr`],
    ["Monthly rent", fmtUSD(inputs.monthlyRent)],
    ["Other income", fmtUSD(inputs.otherIncome ?? 0)],
    ["Property tax", `${inputs.propertyTaxPercent}% of price/yr`],
    ["Insurance", `${fmtUSD(inputs.insuranceMonthly)}/mo`],
    ["Maintenance reserve", `${inputs.maintenancePercent}% of rent`],
    ["Management", `${inputs.managementPercent}% of rent`],
    ["Vacancy", `${inputs.vacancyPercent}%`],
  ];
  doc.setFontSize(9);
  inputPairs.forEach(([k, v]) => {
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 116, 139);
    doc.text(k, MARGIN + 2, y);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 41, 59);
    doc.text(v, MARGIN + 80, y);
    y += 5;
  });

  y += 5;

  // Sensitivity tables
  y = drawSection(doc, "Sensitivity analysis", y);
  doc.setFontSize(8);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(100, 116, 139);
  doc.text(
    "Each row shows how monthly cash flow changes if that input moves while others stay fixed.",
    MARGIN,
    y,
    { maxWidth: CONTENT_WIDTH },
  );
  y += 6;

  for (const table of sensitivity) {
    if (y > 245) {
      doc.addPage();
      y = MARGIN;
    }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(30, 41, 59);
    doc.text(table.axisLabel, MARGIN, y);
    y += 5;

    // Header row
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(100, 116, 139);
    doc.text("Scenario", MARGIN + 2, y);
    doc.text("Cash flow / mo", MARGIN + 60, y);
    doc.text("Cap rate", MARGIN + 105, y);
    doc.text("CoC", MARGIN + 135, y);
    y += 4;
    doc.setDrawColor(226, 232, 240);
    doc.line(MARGIN, y, MARGIN + CONTENT_WIDTH, y);
    y += 3;

    // Data rows
    doc.setFont("helvetica", "normal");
    for (const cell of table.cells) {
      doc.setTextColor(30, 41, 59);
      doc.text(cell.label, MARGIN + 2, y);
      doc.setTextColor(
        cell.monthlyCashFlow >= 0 ? 22 : 185,
        cell.monthlyCashFlow >= 0 ? 163 : 28,
        cell.monthlyCashFlow >= 0 ? 74 : 28,
      );
      doc.text(fmtUSD(cell.monthlyCashFlow), MARGIN + 60, y);
      doc.setTextColor(30, 41, 59);
      doc.text(`${cell.capRate.toFixed(2)}%`, MARGIN + 105, y);
      doc.text(`${cell.cashOnCashReturn.toFixed(1)}%`, MARGIN + 135, y);
      y += 5;
    }
    y += 3;
  }

  doc.setFont("helvetica", "italic");
  doc.setFontSize(7);
  doc.setTextColor(148, 163, 184);
  doc.text(
    "Sensitivity computed client-side from your inputs. No market data — use these as a stress test, not a forecast.",
    MARGIN,
    285,
    { maxWidth: CONTENT_WIDTH },
  );

  return doc;
}

// ── Layout helpers ────────────────────────────────────────────────

function drawSection(doc: jsPDF, title: string, y: number): number {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(30, 41, 59);
  doc.text(title, MARGIN, y);
  return y + 5;
}

function drawParagraph(doc: jsPDF, text: string, y: number): number {
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(51, 65, 85);
  const lines = doc.splitTextToSize(text, CONTENT_WIDTH);
  doc.text(lines, MARGIN, y);
  return y + lines.length * 4.5;
}

function drawBullets(doc: jsPDF, items: string[], y: number): number {
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(51, 65, 85);
  for (const item of items) {
    const lines = doc.splitTextToSize(`• ${item}`, CONTENT_WIDTH - 2);
    doc.text(lines, MARGIN + 2, y);
    y += lines.length * 4.5;
  }
  return y;
}

function fmtUSD(n: number): string {
  if (!Number.isFinite(n)) return "$0";
  const sign = n < 0 ? "−" : "";
  return `${sign}$${Math.abs(Math.round(n)).toLocaleString()}`;
}
