/**
 * Shared types for the AI deal analyzer commentary flow.
 */

export type DealAnalyzerInputs = {
  propertyAddress?: string | null;
  purchasePrice: number;
  bedrooms?: number;
  bathrooms?: number;
  squareFeet?: number;
  yearBuilt?: number | null;

  downPaymentPercent: number;
  interestRate: number;
  loanTermYears: number;

  monthlyRent: number;
  otherIncome?: number;

  propertyTaxPercent: number;
  insuranceMonthly: number;
  maintenancePercent: number;
  managementPercent: number;
  vacancyPercent: number;
};

export type DealAnalyzerMetrics = {
  loanAmount: number;
  monthlyMortgage: number;
  monthlyCashFlow: number;
  annualCashFlow: number;
  annualNOI: number;
  capRate: number;
  cashOnCashReturn: number;
  cashInvested: number;
  priceToRentRatio: number;
};

/**
 * What Claude returns (and what the rule-based fallback mimics).
 * Everything is plain string/number so it serializes cleanly.
 */
export type DealCommentary = {
  dealScore: number; // 0-100
  headline: string; // one-line summary
  summary: string; // 2-3 sentence strategic read
  strengths: string[]; // up to 3
  risks: string[]; // up to 3
  nextMoves: string[]; // up to 3 suggested actions
  /** Whether this was generated by Claude (true) or the rule fallback (false). */
  aiGenerated: boolean;
};
