/** Shared palette for list screens (keeps hot / error / accent consistent). */
export const theme = {
  bg: "#f8fafc",
  surface: "#ffffff",
  surfaceElevated: "#f1f5f9",
  border: "#e2e8f0",
  borderSubtle: "#f1f5f9",
  text: "#0f172a",
  textMuted: "#64748b",
  textSubtle: "#94a3b8",
  accent: "#0072ce",
  accentLight: "#e0f2fe",
  accentDark: "#005ca8",
  success: "#28a745",
  successLight: "#f0fdf4",
  orange: "#ff8c42",
  orangeLight: "#fff7ed",
  errorBg: "#fef2f2",
  errorBorder: "#fecaca",
  errorTitle: "#991b1b",
  errorBody: "#7f1d1d",
  hotBg: "#fff7ed",
  hotBorder: "#ea580c",
  hotPillBg: "#ffedd5",
  hotPillText: "#9a3412",
  hotLabel: "#c2410c",
} as const;
