export type ValuationTrainingExportFilters = {
  minSaleDate?: string;
  maxSaleDate?: string;
  cities?: string[];
  states?: string[];
  propertyTypes?: string[];
  confidenceLabels?: Array<"high" | "medium" | "low">;
  minComparableCount?: number;
  maxErrorPct?: number;
  requireSqft?: boolean;
  requireApiEstimate?: boolean;
  requireCompsEstimate?: boolean;
};

export type ValuationTrainingRow = {
  id: string;
  lead_id?: number | null;
  property_address: string;
  city?: string | null;
  state?: string | null;
  zip?: string | null;
  property_type?: string | null;
  beds?: number | string | null;
  baths?: number | string | null;
  sqft?: number | null;
  lot_size?: number | null;
  year_built?: number | null;
  condition?: string | null;
  remodeled_year?: number | null;
  api_estimate?: number | string | null;
  comps_estimate?: number | string | null;
  tax_anchor_estimate?: number | string | null;
  final_estimate: number | string;
  low_estimate: number | string;
  high_estimate: number | string;
  confidence_score: number | string;
  confidence_label: string;
  comparable_count: number | string;
  weighted_ppsf?: number | string | null;
  listing_trend_adjustment_pct: number | string;
  condition_adjustment_pct: number | string;
  range_spread_pct: number | string;
  tier_used?: string | null;
  valuation_version: string;
  actual_sale_price: number | string;
  actual_sale_date?: string | null;
  actual_days_from_estimate?: number | null;
  error_amount?: number | string | null;
  error_pct?: number | string | null;
  inside_range?: boolean | null;
  created_at: string;
  lead_source?: string | null;
  lead_intent?: string | null;
  lead_price?: number | string | null;
  lead_score?: number | string | null;
  lead_temperature?: string | null;
  engagement_score?: number | string | null;
  source_session_id?: string | null;
  landing_page?: string | null;
  seo_slug?: string | null;
  /** Enrichment (see normalize.ts) */
  api_vs_comps_diff_pct?: number | null;
  tax_vs_comps_diff_pct?: number | null;
  tax_vs_api_diff_pct?: number | null;
  months_since_last_sale?: number | null;
  months_from_estimate_to_sale?: number | null;
};
